name = "StructuredMechModels"
uuid = "49eb0842-c156-4c0e-b374-fa0a2422abc2"
authors = ["rejuvyesh <mail@rejuvyesh.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
